# Generated by Django 5.1.3 on 2024-11-13 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motorista', '0002_motorista_cnh'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoristaLoginFront',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.TextField(max_length=20)),
                ('senha', models.TextField(max_length=200)),
                ('telefone', models.TextField(max_length=20)),
                ('motorista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='motorista.motorista')),
            ],
        ),
    ]
