# Generated by Django 5.1.3 on 2024-11-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_motorista', models.TextField(max_length=255)),
                ('placa_veiculo', models.TextField(max_length=255)),
                ('pessoa_fisica', models.BooleanField()),
            ],
        ),
    ]
