# Generated by Django 5.1.3 on 2024-11-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='cnh',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
